#!/usr/bin/env ruby

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'gh/events'

ARGV.each do |file|
  begin
    type = GH::Events.typeof(File.read(file))
  rescue
    type = 'error'
  end
  puts "#{file}: #{type}"
end
